import Foundation

struct Emoji: Identifiable, Equatable {
    var id: String { char }
    let char: String
    let name: String
    let keywords: [String]
    let group: String
}

enum EmojiCatalog {
    static let all: [Emoji] = [
        Emoji(char: "😀", name: "rosto sorrindo", keywords: ["feliz", "sorriso", "happy", "smile", "grinning"], group: "Smileys"),
        Emoji(char: "😃", name: "rosto sorrindo com olhos abertos", keywords: ["feliz", "alegre", "happy", "smiley"], group: "Smileys"),
        Emoji(char: "😄", name: "rosto sorrindo com olhos fechados", keywords: ["feliz", "risada", "laugh", "happy"], group: "Smileys"),
        Emoji(char: "😁", name: "rosto sorrindo com dentes", keywords: ["feliz", "grin", "sorriso"], group: "Smileys"),
        Emoji(char: "😆", name: "rosto rindo", keywords: ["risada", "laugh", "haha"], group: "Smileys"),
        Emoji(char: "😅", name: "rosto suando de rir", keywords: ["risada", "nervoso", "sweat", "laugh"], group: "Smileys"),
        Emoji(char: "🤣", name: "rolando de rir", keywords: ["rofl", "risada", "morrendo de rir", "lol"], group: "Smileys"),
        Emoji(char: "😂", name: "rindo até chorar", keywords: ["lágrimas de alegria", "lol", "kkk", "risada"], group: "Smileys"),
        Emoji(char: "🙂", name: "rosto levemente sorrindo", keywords: ["sorriso", "smile", "ok"], group: "Smileys"),
        Emoji(char: "🙃", name: "rosto de cabeça para baixo", keywords: ["upside down", "ironia", "sarcasmo"], group: "Smileys"),
        Emoji(char: "😉", name: "piscando", keywords: ["wink", "piscadela", "flerte"], group: "Smileys"),
        Emoji(char: "😊", name: "rosto sorrindo com olhos fechados corado", keywords: ["feliz", "blush", "sorriso", "smile"], group: "Smileys"),
        Emoji(char: "😇", name: "rosto de anjo", keywords: ["inocente", "angel", "halo", "santo"], group: "Smileys"),
        Emoji(char: "🥰", name: "rosto apaixonado sorrindo", keywords: ["amor", "love", "corações", "carinho"], group: "Smileys"),
        Emoji(char: "😍", name: "rosto com olhos de coração", keywords: ["amor", "love", "apaixonado", "heart eyes"], group: "Smileys"),
        Emoji(char: "🤩", name: "rosto maravilhado", keywords: ["estrelas", "star struck", "impressionado"], group: "Smileys"),
        Emoji(char: "😘", name: "rosto mandando beijo", keywords: ["beijo", "kiss", "amor"], group: "Smileys"),
        Emoji(char: "😗", name: "rosto beijando", keywords: ["beijo", "kiss"], group: "Smileys"),
        Emoji(char: "😚", name: "rosto beijando com olhos fechados", keywords: ["beijo", "kiss"], group: "Smileys"),
        Emoji(char: "😙", name: "rosto beijando sorrindo", keywords: ["beijo", "kiss"], group: "Smileys"),
        Emoji(char: "😋", name: "rosto saboreando comida", keywords: ["gostoso", "yummy", "delicioso", "fome"], group: "Smileys"),
        Emoji(char: "😛", name: "rosto com a língua de fora", keywords: ["língua", "tongue", "brincalhão"], group: "Smileys"),
        Emoji(char: "😜", name: "piscando com a língua de fora", keywords: ["língua", "tongue", "wink"], group: "Smileys"),
        Emoji(char: "🤪", name: "rosto de doido", keywords: ["louco", "crazy", "zany"], group: "Smileys"),
        Emoji(char: "😝", name: "olhos fechados com a língua de fora", keywords: ["língua", "tongue"], group: "Smileys"),
        Emoji(char: "🤑", name: "rosto com olhos de dinheiro", keywords: ["dinheiro", "money", "grana"], group: "Smileys"),
        Emoji(char: "🤗", name: "rosto abraçando", keywords: ["abraço", "hug", "carinho"], group: "Smileys"),
        Emoji(char: "🤭", name: "mão tapando a boca", keywords: ["tímido", "oops", "shy"], group: "Smileys"),
        Emoji(char: "🤫", name: "rosto pedindo silêncio", keywords: ["silêncio", "shh", "quiet"], group: "Smileys"),
        Emoji(char: "🤔", name: "rosto pensativo", keywords: ["pensando", "thinking", "hmm", "dúvida"], group: "Smileys"),
        Emoji(char: "🤐", name: "rosto com zíper na boca", keywords: ["quieto", "zipper", "segredo"], group: "Smileys"),
        Emoji(char: "🤨", name: "sobrancelha levantada", keywords: ["desconfiado", "raised eyebrow", "suspeito"], group: "Smileys"),
        Emoji(char: "😐", name: "rosto neutro", keywords: ["neutral", "sem expressão", "meh"], group: "Smileys"),
        Emoji(char: "😑", name: "rosto sem expressão", keywords: ["expressionless", "tédio"], group: "Smileys"),
        Emoji(char: "😶", name: "rosto sem boca", keywords: ["mudo", "no mouth", "silêncio"], group: "Smileys"),
        Emoji(char: "😏", name: "rosto de deboche", keywords: ["smirk", "irônico", "malicioso"], group: "Smileys"),
        Emoji(char: "😒", name: "rosto contrariado", keywords: ["unamused", "chateado", "sem paciência"], group: "Smileys"),
        Emoji(char: "🙄", name: "revirando os olhos", keywords: ["eye roll", "tédio", "irritado"], group: "Smileys"),
        Emoji(char: "😬", name: "rosto encabulado", keywords: ["grimace", "constrangido", "vergonha"], group: "Smileys"),
        Emoji(char: "🤥", name: "rosto de mentiroso", keywords: ["mentira", "lying", "pinóquio"], group: "Smileys"),
        Emoji(char: "😌", name: "rosto aliviado", keywords: ["relieved", "alívio", "calma"], group: "Smileys"),
        Emoji(char: "😔", name: "rosto pensativo triste", keywords: ["triste", "sad", "pensive"], group: "Smileys"),
        Emoji(char: "😪", name: "rosto sonolento", keywords: ["sono", "sleepy", "cansado"], group: "Smileys"),
        Emoji(char: "🤤", name: "rosto babando", keywords: ["drooling", "baba", "desejo"], group: "Smileys"),
        Emoji(char: "😴", name: "rosto dormindo", keywords: ["sono", "sleeping", "zzz"], group: "Smileys"),
        Emoji(char: "😷", name: "rosto com máscara", keywords: ["doente", "máscara", "mask", "gripe"], group: "Smileys"),
        Emoji(char: "🤒", name: "rosto com termômetro", keywords: ["doente", "febre", "sick"], group: "Smileys"),
        Emoji(char: "🤕", name: "rosto com curativo", keywords: ["machucado", "injured", "hurt"], group: "Smileys"),
        Emoji(char: "🤢", name: "rosto enjoado", keywords: ["nojo", "nauseated", "enjoo"], group: "Smileys"),
        Emoji(char: "🤮", name: "rosto vomitando", keywords: ["vômito", "vomiting", "nojo"], group: "Smileys"),
        Emoji(char: "🤧", name: "rosto espirrando", keywords: ["espirro", "sneezing", "gripe"], group: "Smileys"),
        Emoji(char: "🥵", name: "rosto com calor", keywords: ["calor", "hot", "suando"], group: "Smileys"),
        Emoji(char: "🥶", name: "rosto com frio", keywords: ["frio", "cold", "gelado"], group: "Smileys"),
        Emoji(char: "🥴", name: "rosto zonzo", keywords: ["tonto", "woozy", "bêbado"], group: "Smileys"),
        Emoji(char: "😵", name: "rosto zonzo tonto", keywords: ["dizzy", "tonto", "confuso"], group: "Smileys"),
        Emoji(char: "🤯", name: "cabeça explodindo", keywords: ["mind blown", "chocado", "surpreso"], group: "Smileys"),
        Emoji(char: "🤠", name: "rosto com chapéu de cowboy", keywords: ["cowboy", "chapéu", "vaqueiro"], group: "Smileys"),
        Emoji(char: "🥳", name: "rosto de festa", keywords: ["festa", "party", "comemoração", "parabéns"], group: "Smileys"),
        Emoji(char: "🥸", name: "rosto disfarçado", keywords: ["disfarce", "disguise", "bigode"], group: "Smileys"),
        Emoji(char: "😎", name: "rosto com óculos escuros", keywords: ["legal", "cool", "óculos"], group: "Smileys"),
        Emoji(char: "🤓", name: "rosto de nerd", keywords: ["nerd", "óculos", "cdf"], group: "Smileys"),
        Emoji(char: "🧐", name: "rosto com monóculo", keywords: ["monóculo", "curioso", "investigando"], group: "Smileys"),
        Emoji(char: "😕", name: "rosto confuso", keywords: ["confused", "confuso", "dúvida"], group: "Smileys"),
        Emoji(char: "😟", name: "rosto preocupado", keywords: ["worried", "preocupado", "ansioso"], group: "Smileys"),
        Emoji(char: "🙁", name: "rosto levemente franzido", keywords: ["frowning", "triste", "chateado"], group: "Smileys"),
        Emoji(char: "☹️", name: "rosto franzido", keywords: ["frowning", "triste"], group: "Smileys"),
        Emoji(char: "😮", name: "rosto de boca aberta", keywords: ["surpreso", "surprised", "oh", "wow"], group: "Smileys"),
        Emoji(char: "😯", name: "rosto atônito", keywords: ["hushed", "surpreso", "silêncio"], group: "Smileys"),
        Emoji(char: "😲", name: "rosto pasmo", keywords: ["astonished", "chocado", "surpreso"], group: "Smileys"),
        Emoji(char: "😳", name: "rosto ruborizado", keywords: ["flushed", "vergonha", "constrangido"], group: "Smileys"),
        Emoji(char: "🥺", name: "rosto de súplica", keywords: ["pleading", "pidão", "carinha triste"], group: "Smileys"),
        Emoji(char: "😦", name: "rosto franzido com boca aberta", keywords: ["frowning", "chocado"], group: "Smileys"),
        Emoji(char: "😧", name: "rosto angustiado", keywords: ["anguished", "sofrendo"], group: "Smileys"),
        Emoji(char: "😨", name: "rosto com medo", keywords: ["fearful", "medo", "assustado"], group: "Smileys"),
        Emoji(char: "😰", name: "rosto ansioso suando frio", keywords: ["anxious", "ansioso", "nervoso"], group: "Smileys"),
        Emoji(char: "😥", name: "rosto triste mas aliviado", keywords: ["sad", "triste", "alívio"], group: "Smileys"),
        Emoji(char: "😢", name: "rosto chorando", keywords: ["choro", "crying", "triste", "lágrima"], group: "Smileys"),
        Emoji(char: "😭", name: "chorando muito", keywords: ["choro", "sobbing", "triste demais"], group: "Smileys"),
        Emoji(char: "😱", name: "rosto gritando de medo", keywords: ["scream", "grito", "medo", "susto"], group: "Smileys"),
        Emoji(char: "😖", name: "rosto confuso e angustiado", keywords: ["confounded", "irritado"], group: "Smileys"),
        Emoji(char: "😣", name: "rosto perseverante", keywords: ["persevering", "esforço"], group: "Smileys"),
        Emoji(char: "😞", name: "rosto desapontado", keywords: ["disappointed", "decepcionado"], group: "Smileys"),
        Emoji(char: "😓", name: "rosto suando", keywords: ["downcast", "suando", "cansado"], group: "Smileys"),
        Emoji(char: "😩", name: "rosto exausto", keywords: ["weary", "cansado", "exausto"], group: "Smileys"),
        Emoji(char: "😫", name: "rosto esgotado", keywords: ["tired", "esgotado", "cansado"], group: "Smileys"),
        Emoji(char: "🥱", name: "rosto bocejando", keywords: ["yawning", "bocejo", "sono"], group: "Smileys"),
        Emoji(char: "😤", name: "rosto bufando", keywords: ["triumph", "raiva", "irritado"], group: "Smileys"),
        Emoji(char: "😡", name: "rosto de raiva", keywords: ["angry", "raiva", "furioso", "bravo"], group: "Smileys"),
        Emoji(char: "😠", name: "rosto zangado", keywords: ["angry", "bravo", "irritado"], group: "Smileys"),
        Emoji(char: "🤬", name: "rosto praguejando", keywords: ["swearing", "xingando", "raiva"], group: "Smileys"),
        Emoji(char: "😈", name: "rosto sorridente diabinho", keywords: ["diabo", "devil", "malvado"], group: "Smileys"),
        Emoji(char: "👿", name: "rosto de diabo zangado", keywords: ["devil", "raiva", "imp"], group: "Smileys"),
        Emoji(char: "💀", name: "caveira", keywords: ["skull", "morte", "morrendo de rir"], group: "Smileys"),
        Emoji(char: "☠️", name: "caveira com ossos cruzados", keywords: ["skull crossbones", "perigo", "veneno"], group: "Smileys"),
        Emoji(char: "🤡", name: "rosto de palhaço", keywords: ["clown", "palhaço", "bobo"], group: "Smileys"),
        Emoji(char: "👹", name: "ogro", keywords: ["ogre", "monstro"], group: "Smileys"),
        Emoji(char: "👻", name: "fantasma", keywords: ["ghost", "assombração", "halloween"], group: "Smileys"),
        Emoji(char: "👽", name: "alienígena", keywords: ["alien", "et", "extraterrestre"], group: "Smileys"),
        Emoji(char: "🤖", name: "robô", keywords: ["robot", "robô", "ia"], group: "Smileys"),
        Emoji(char: "😺", name: "gato sorrindo", keywords: ["gato", "cat", "sorriso"], group: "Smileys"),
        Emoji(char: "😹", name: "gato rindo até chorar", keywords: ["gato", "cat", "risada"], group: "Smileys"),
        Emoji(char: "😻", name: "gato com olhos de coração", keywords: ["gato", "cat", "amor"], group: "Smileys"),

        Emoji(char: "👍", name: "joinha", keywords: ["joinha", "positivo", "thumbs up", "curtir", "ok"], group: "Gestos"),
        Emoji(char: "👎", name: "joinha negativo", keywords: ["negativo", "thumbs down", "não curti"], group: "Gestos"),
        Emoji(char: "👌", name: "sinal de ok", keywords: ["ok", "perfeito", "beleza"], group: "Gestos"),
        Emoji(char: "✌️", name: "sinal de paz", keywords: ["paz", "vitória", "peace", "vitoria"], group: "Gestos"),
        Emoji(char: "🤞", name: "dedos cruzados", keywords: ["sorte", "fingers crossed", "torcendo"], group: "Gestos"),
        Emoji(char: "🤟", name: "sinal de eu te amo", keywords: ["te amo", "love you", "rock"], group: "Gestos"),
        Emoji(char: "🤘", name: "sinal de rock", keywords: ["rock", "metal", "chifrinho"], group: "Gestos"),
        Emoji(char: "🤙", name: "sinal de ligação hang loose", keywords: ["ligação", "call me", "surf"], group: "Gestos"),
        Emoji(char: "👈", name: "apontando para a esquerda", keywords: ["esquerda", "left", "apontar"], group: "Gestos"),
        Emoji(char: "👉", name: "apontando para a direita", keywords: ["direita", "right", "apontar"], group: "Gestos"),
        Emoji(char: "👆", name: "apontando para cima", keywords: ["cima", "up", "apontar"], group: "Gestos"),
        Emoji(char: "🖕", name: "dedo do meio", keywords: ["middle finger", "ofensa"], group: "Gestos"),
        Emoji(char: "👇", name: "apontando para baixo", keywords: ["baixo", "down", "apontar"], group: "Gestos"),
        Emoji(char: "☝️", name: "dedo indicador para cima", keywords: ["atenção", "index", "up"], group: "Gestos"),
        Emoji(char: "👋", name: "mão acenando", keywords: ["tchau", "oi", "wave", "olá"], group: "Gestos"),
        Emoji(char: "🤚", name: "dorso da mão levantada", keywords: ["parar", "stop", "mão"], group: "Gestos"),
        Emoji(char: "🖐️", name: "mão aberta", keywords: ["mão", "hand", "cinco"], group: "Gestos"),
        Emoji(char: "✋", name: "mão levantada", keywords: ["parar", "high five", "mão"], group: "Gestos"),
        Emoji(char: "🖖", name: "saudação vulcana", keywords: ["spock", "star trek", "vulcano"], group: "Gestos"),
        Emoji(char: "👏", name: "mãos batendo palmas", keywords: ["palmas", "clap", "aplausos", "parabéns"], group: "Gestos"),
        Emoji(char: "🙌", name: "mãos levantadas", keywords: ["comemorar", "raise hands", "hooray"], group: "Gestos"),
        Emoji(char: "👐", name: "mãos abertas", keywords: ["abraço", "open hands"], group: "Gestos"),
        Emoji(char: "🤲", name: "palmas juntas para cima", keywords: ["oferecer", "prece"], group: "Gestos"),
        Emoji(char: "🤝", name: "aperto de mãos", keywords: ["handshake", "acordo", "negócio"], group: "Gestos"),
        Emoji(char: "🙏", name: "mãos em prece", keywords: ["por favor", "obrigado", "prece", "please", "thanks"], group: "Gestos"),
        Emoji(char: "✍️", name: "mão escrevendo", keywords: ["escrever", "write", "caneta"], group: "Gestos"),
        Emoji(char: "💪", name: "bíceps flexionado", keywords: ["força", "musculo", "strong", "forte"], group: "Gestos"),
        Emoji(char: "🦾", name: "braço mecânico", keywords: ["prótese", "robótico"], group: "Gestos"),
        Emoji(char: "🧠", name: "cérebro", keywords: ["brain", "inteligência", "pensar"], group: "Gestos"),

        Emoji(char: "❤️", name: "coração vermelho", keywords: ["amor", "coracao", "coração", "love", "heart"], group: "Corações"),
        Emoji(char: "🧡", name: "coração laranja", keywords: ["coração", "coracao", "orange heart"], group: "Corações"),
        Emoji(char: "💛", name: "coração amarelo", keywords: ["coração", "coracao", "yellow heart", "amizade"], group: "Corações"),
        Emoji(char: "💚", name: "coração verde", keywords: ["coração", "coracao", "green heart"], group: "Corações"),
        Emoji(char: "💙", name: "coração azul", keywords: ["coração", "coracao", "blue heart"], group: "Corações"),
        Emoji(char: "💜", name: "coração roxo", keywords: ["coração", "coracao", "purple heart"], group: "Corações"),
        Emoji(char: "🖤", name: "coração preto", keywords: ["coração", "coracao", "black heart"], group: "Corações"),
        Emoji(char: "🤍", name: "coração branco", keywords: ["coração", "coracao", "white heart"], group: "Corações"),
        Emoji(char: "🤎", name: "coração marrom", keywords: ["coração", "coracao", "brown heart"], group: "Corações"),
        Emoji(char: "💔", name: "coração partido", keywords: ["coração partido", "coracao partido", "broken heart", "fim"], group: "Corações"),
        Emoji(char: "❣️", name: "exclamação de coração", keywords: ["coração", "coracao", "heart exclamation"], group: "Corações"),
        Emoji(char: "💕", name: "dois corações", keywords: ["amor", "coracao", "coração", "two hearts"], group: "Corações"),
        Emoji(char: "💞", name: "corações girando", keywords: ["amor", "revolving hearts"], group: "Corações"),
        Emoji(char: "💓", name: "coração pulsando", keywords: ["batendo", "beating heart"], group: "Corações"),
        Emoji(char: "💗", name: "coração crescendo", keywords: ["growing heart", "carinho"], group: "Corações"),
        Emoji(char: "💖", name: "coração brilhante", keywords: ["sparkling heart", "brilho"], group: "Corações"),
        Emoji(char: "💘", name: "coração com flecha", keywords: ["cupido", "arrow through heart", "paixão"], group: "Corações"),
        Emoji(char: "💝", name: "coração com laço", keywords: ["presente", "heart with ribbon"], group: "Corações"),
        Emoji(char: "💟", name: "decoração de coração", keywords: ["heart decoration"], group: "Corações"),

        Emoji(char: "🐶", name: "rosto de cachorro", keywords: ["cachorro", "dog", "cão", "pet"], group: "Animais"),
        Emoji(char: "🐱", name: "rosto de gato", keywords: ["gato", "cat", "felino"], group: "Animais"),
        Emoji(char: "🐭", name: "rosto de rato", keywords: ["rato", "mouse", "camundongo"], group: "Animais"),
        Emoji(char: "🐹", name: "rosto de hamster", keywords: ["hamster"], group: "Animais"),
        Emoji(char: "🐰", name: "rosto de coelho", keywords: ["coelho", "rabbit"], group: "Animais"),
        Emoji(char: "🦊", name: "rosto de raposa", keywords: ["raposa", "fox"], group: "Animais"),
        Emoji(char: "🐻", name: "rosto de urso", keywords: ["urso", "bear"], group: "Animais"),
        Emoji(char: "🐼", name: "panda", keywords: ["panda"], group: "Animais"),
        Emoji(char: "🐨", name: "coala", keywords: ["coala", "koala"], group: "Animais"),
        Emoji(char: "🐯", name: "rosto de tigre", keywords: ["tigre", "tiger"], group: "Animais"),
        Emoji(char: "🦁", name: "rosto de leão", keywords: ["leão", "lion"], group: "Animais"),
        Emoji(char: "🐮", name: "rosto de vaca", keywords: ["vaca", "cow", "boi"], group: "Animais"),
        Emoji(char: "🐷", name: "rosto de porco", keywords: ["porco", "pig"], group: "Animais"),
        Emoji(char: "🐸", name: "sapo", keywords: ["sapo", "frog"], group: "Animais"),
        Emoji(char: "🐵", name: "rosto de macaco", keywords: ["macaco", "monkey"], group: "Animais"),
        Emoji(char: "🐔", name: "galinha", keywords: ["galinha", "chicken"], group: "Animais"),
        Emoji(char: "🐧", name: "pinguim", keywords: ["pinguim", "penguin"], group: "Animais"),
        Emoji(char: "🐦", name: "pássaro", keywords: ["pássaro", "passaro", "bird"], group: "Animais"),
        Emoji(char: "🦆", name: "pato", keywords: ["pato", "duck"], group: "Animais"),
        Emoji(char: "🦉", name: "coruja", keywords: ["coruja", "owl"], group: "Animais"),
        Emoji(char: "🐴", name: "rosto de cavalo", keywords: ["cavalo", "horse"], group: "Animais"),
        Emoji(char: "🦄", name: "unicórnio", keywords: ["unicornio", "unicórnio", "unicorn"], group: "Animais"),
        Emoji(char: "🐝", name: "abelha", keywords: ["abelha", "bee"], group: "Animais"),
        Emoji(char: "🐛", name: "lagarta", keywords: ["lagarta", "bug", "inseto"], group: "Animais"),
        Emoji(char: "🦋", name: "borboleta", keywords: ["borboleta", "butterfly"], group: "Animais"),
        Emoji(char: "🐌", name: "caracol", keywords: ["caracol", "snail"], group: "Animais"),
        Emoji(char: "🐢", name: "tartaruga", keywords: ["tartaruga", "turtle"], group: "Animais"),
        Emoji(char: "🐍", name: "cobra", keywords: ["cobra", "snake"], group: "Animais"),
        Emoji(char: "🐙", name: "polvo", keywords: ["polvo", "octopus"], group: "Animais"),
        Emoji(char: "🐬", name: "golfinho", keywords: ["golfinho", "dolphin"], group: "Animais"),
        Emoji(char: "🐳", name: "baleia", keywords: ["baleia", "whale"], group: "Animais"),
        Emoji(char: "🐟", name: "peixe", keywords: ["peixe", "fish"], group: "Animais"),

        Emoji(char: "🍎", name: "maçã vermelha", keywords: ["maçã", "maca", "apple", "fruta"], group: "Comida"),
        Emoji(char: "🍌", name: "banana", keywords: ["banana"], group: "Comida"),
        Emoji(char: "🍇", name: "uvas", keywords: ["uva", "grape"], group: "Comida"),
        Emoji(char: "🍉", name: "melancia", keywords: ["melancia", "watermelon"], group: "Comida"),
        Emoji(char: "🍊", name: "laranja", keywords: ["laranja", "orange", "tangerina"], group: "Comida"),
        Emoji(char: "🍓", name: "morango", keywords: ["morango", "strawberry"], group: "Comida"),
        Emoji(char: "🍍", name: "abacaxi", keywords: ["abacaxi", "pineapple"], group: "Comida"),
        Emoji(char: "🥑", name: "abacate", keywords: ["abacate", "avocado"], group: "Comida"),
        Emoji(char: "🍅", name: "tomate", keywords: ["tomate", "tomato"], group: "Comida"),
        Emoji(char: "🌽", name: "milho", keywords: ["milho", "corn"], group: "Comida"),
        Emoji(char: "🥕", name: "cenoura", keywords: ["cenoura", "carrot"], group: "Comida"),
        Emoji(char: "🍞", name: "pão", keywords: ["pão", "pao", "bread"], group: "Comida"),
        Emoji(char: "🧀", name: "queijo", keywords: ["queijo", "cheese"], group: "Comida"),
        Emoji(char: "🍳", name: "ovo frito", keywords: ["ovo", "egg", "fritando"], group: "Comida"),
        Emoji(char: "🍔", name: "hambúrguer", keywords: ["hamburguer", "hambúrguer", "burger", "lanche"], group: "Comida"),
        Emoji(char: "🍟", name: "batata frita", keywords: ["batata frita", "fries"], group: "Comida"),
        Emoji(char: "🍕", name: "pizza", keywords: ["pizza"], group: "Comida"),
        Emoji(char: "🌭", name: "cachorro-quente", keywords: ["cachorro quente", "hot dog"], group: "Comida"),
        Emoji(char: "🌮", name: "taco", keywords: ["taco", "mexicano"], group: "Comida"),
        Emoji(char: "🍝", name: "espaguete", keywords: ["macarrão", "macarrao", "pasta", "espaguete"], group: "Comida"),
        Emoji(char: "🍜", name: "macarrão em tigela", keywords: ["macarrão", "macarrao", "ramen", "sopa"], group: "Comida"),
        Emoji(char: "🍣", name: "sushi", keywords: ["sushi", "japonês", "japones"], group: "Comida"),
        Emoji(char: "🍦", name: "sorvete soft", keywords: ["sorvete", "ice cream"], group: "Comida"),
        Emoji(char: "🍩", name: "rosquinha", keywords: ["rosquinha", "donut", "doce"], group: "Comida"),
        Emoji(char: "🍪", name: "biscoito", keywords: ["biscoito", "cookie"], group: "Comida"),
        Emoji(char: "🎂", name: "bolo de aniversário", keywords: ["bolo", "cake", "aniversário", "aniversario"], group: "Comida"),
        Emoji(char: "🍫", name: "chocolate", keywords: ["chocolate"], group: "Comida"),
        Emoji(char: "🍿", name: "pipoca", keywords: ["pipoca", "popcorn"], group: "Comida"),
        Emoji(char: "☕", name: "café quente", keywords: ["café", "cafe", "coffee"], group: "Comida"),
        Emoji(char: "🍺", name: "cerveja", keywords: ["cerveja", "beer"], group: "Comida"),
        Emoji(char: "🍷", name: "taça de vinho", keywords: ["vinho", "wine"], group: "Comida"),
        Emoji(char: "🥤", name: "copo com canudo", keywords: ["refrigerante", "bebida", "drink"], group: "Comida"),

        Emoji(char: "📱", name: "celular", keywords: ["celular", "phone", "smartphone"], group: "Objetos"),
        Emoji(char: "💻", name: "laptop", keywords: ["computador", "laptop", "notebook"], group: "Objetos"),
        Emoji(char: "⌨️", name: "teclado", keywords: ["teclado", "keyboard"], group: "Objetos"),
        Emoji(char: "🖥️", name: "computador de mesa", keywords: ["computador", "desktop", "monitor"], group: "Objetos"),
        Emoji(char: "🖱️", name: "mouse de computador", keywords: ["mouse"], group: "Objetos"),
        Emoji(char: "📷", name: "câmera", keywords: ["câmera", "camera", "foto"], group: "Objetos"),
        Emoji(char: "🎥", name: "câmera de vídeo", keywords: ["vídeo", "video", "filmagem"], group: "Objetos"),
        Emoji(char: "🔋", name: "bateria", keywords: ["bateria", "battery", "carga"], group: "Objetos"),
        Emoji(char: "🔌", name: "plugue elétrico", keywords: ["plugue", "carregador", "energia"], group: "Objetos"),
        Emoji(char: "💡", name: "lâmpada", keywords: ["lâmpada", "lampada", "ideia", "luz"], group: "Objetos"),
        Emoji(char: "🔦", name: "lanterna", keywords: ["lanterna", "flashlight"], group: "Objetos"),
        Emoji(char: "🕯️", name: "vela", keywords: ["vela", "candle"], group: "Objetos"),
        Emoji(char: "📚", name: "livros", keywords: ["livros", "books", "leitura", "estudo"], group: "Objetos"),
        Emoji(char: "📖", name: "livro aberto", keywords: ["livro", "book"], group: "Objetos"),
        Emoji(char: "✏️", name: "lápis", keywords: ["lápis", "lapis", "pencil"], group: "Objetos"),
        Emoji(char: "🖊️", name: "caneta", keywords: ["caneta", "pen"], group: "Objetos"),
        Emoji(char: "📝", name: "memorando", keywords: ["nota", "anotação", "memo", "note"], group: "Objetos"),
        Emoji(char: "📎", name: "clipe de papel", keywords: ["clipe", "paperclip", "anexo"], group: "Objetos"),
        Emoji(char: "📌", name: "alfinete", keywords: ["pin", "fixar", "alfinete"], group: "Objetos"),
        Emoji(char: "✂️", name: "tesoura", keywords: ["tesoura", "scissors", "cortar"], group: "Objetos"),
        Emoji(char: "🔒", name: "cadeado fechado", keywords: ["cadeado", "lock", "seguro", "privado"], group: "Objetos"),
        Emoji(char: "🔑", name: "chave", keywords: ["chave", "key", "senha"], group: "Objetos"),
        Emoji(char: "🔨", name: "martelo", keywords: ["martelo", "hammer"], group: "Objetos"),
        Emoji(char: "🛠️", name: "chave e chave inglesa", keywords: ["ferramentas", "tools", "conserto"], group: "Objetos"),
        Emoji(char: "💰", name: "saco de dinheiro", keywords: ["dinheiro", "money", "grana"], group: "Objetos"),
        Emoji(char: "💳", name: "cartão de crédito", keywords: ["cartão", "cartao", "credit card"], group: "Objetos"),
        Emoji(char: "🎁", name: "presente", keywords: ["presente", "gift"], group: "Objetos"),
        Emoji(char: "🎈", name: "balão", keywords: ["balão", "balao", "balloon", "festa"], group: "Objetos"),
        Emoji(char: "🎉", name: "confete comemorativo", keywords: ["comemoração", "festa", "party", "parabéns", "tada"], group: "Objetos"),
        Emoji(char: "🎊", name: "bola de confete", keywords: ["confete", "festa", "comemoração"], group: "Objetos"),
        Emoji(char: "🏆", name: "troféu", keywords: ["troféu", "trofeu", "trophy", "vitória", "campeão"], group: "Objetos"),
        Emoji(char: "🎮", name: "controle de videogame", keywords: ["jogo", "game", "videogame", "controle"], group: "Objetos"),
        Emoji(char: "🎧", name: "fones de ouvido", keywords: ["fone", "headphones", "música"], group: "Objetos"),
        Emoji(char: "🎵", name: "nota musical", keywords: ["música", "musica", "music", "nota"], group: "Objetos"),
        Emoji(char: "🔥", name: "fogo", keywords: ["fogo", "fire", "quente", "top"], group: "Objetos"),
        Emoji(char: "💧", name: "gota", keywords: ["água", "agua", "drop", "gota"], group: "Objetos"),
        Emoji(char: "⭐", name: "estrela", keywords: ["estrela", "star"], group: "Objetos"),
        Emoji(char: "✨", name: "brilhos", keywords: ["brilho", "sparkles", "mágico"], group: "Objetos"),
        Emoji(char: "⏰", name: "despertador", keywords: ["despertador", "alarm", "hora"], group: "Objetos"),
        Emoji(char: "📅", name: "calendário", keywords: ["calendário", "calendario", "calendar", "data"], group: "Objetos"),

        Emoji(char: "✅", name: "marca de verificação", keywords: ["check", "certo", "feito", "ok"], group: "Símbolos"),
        Emoji(char: "❌", name: "marca x", keywords: ["errado", "cancel", "x", "não"], group: "Símbolos"),
        Emoji(char: "⚠️", name: "aviso", keywords: ["atenção", "warning", "cuidado", "alerta"], group: "Símbolos"),
        Emoji(char: "❗", name: "ponto de exclamação", keywords: ["exclamação", "exclamacao", "importante"], group: "Símbolos"),
        Emoji(char: "❓", name: "ponto de interrogação", keywords: ["interrogação", "pergunta", "dúvida"], group: "Símbolos"),
        Emoji(char: "💯", name: "cem pontos", keywords: ["cem", "100", "perfeito", "top"], group: "Símbolos"),
        Emoji(char: "🔴", name: "círculo vermelho", keywords: ["vermelho", "red circle", "gravando"], group: "Símbolos"),
        Emoji(char: "🟢", name: "círculo verde", keywords: ["verde", "green circle", "online"], group: "Símbolos"),
        Emoji(char: "🟡", name: "círculo amarelo", keywords: ["amarelo", "yellow circle"], group: "Símbolos"),
        Emoji(char: "🔵", name: "círculo azul", keywords: ["azul", "blue circle"], group: "Símbolos"),
        Emoji(char: "⚡", name: "raio", keywords: ["raio", "lightning", "rápido", "energia"], group: "Símbolos"),
        Emoji(char: "♻️", name: "símbolo de reciclagem", keywords: ["reciclagem", "recycle", "sustentável"], group: "Símbolos"),
        Emoji(char: "🔞", name: "proibido menores de 18", keywords: ["18+", "adulto", "proibido"], group: "Símbolos"),
        Emoji(char: "🆗", name: "botão ok", keywords: ["ok", "beleza"], group: "Símbolos"),
        Emoji(char: "🆕", name: "botão novo", keywords: ["novo", "new"], group: "Símbolos"),
        Emoji(char: "➡️", name: "seta para a direita", keywords: ["seta", "arrow", "direita"], group: "Símbolos"),
        Emoji(char: "⬅️", name: "seta para a esquerda", keywords: ["seta", "arrow", "esquerda"], group: "Símbolos"),
        Emoji(char: "🔁", name: "repetir", keywords: ["repetir", "repeat", "loop"], group: "Símbolos"),
        Emoji(char: "🔀", name: "embaralhar", keywords: ["shuffle", "aleatório", "misturar"], group: "Símbolos"),

        Emoji(char: "🇧🇷", name: "bandeira do Brasil", keywords: ["brasil", "brazil", "bandeira"], group: "Bandeiras"),
        Emoji(char: "🇺🇸", name: "bandeira dos Estados Unidos", keywords: ["estados unidos", "eua", "usa", "bandeira"], group: "Bandeiras"),
        Emoji(char: "🇵🇹", name: "bandeira de Portugal", keywords: ["portugal", "bandeira"], group: "Bandeiras"),
    ]
}
